[package]
name = "qrap-sim"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
qrap-crypto = { workspace = true }
qrap-net = { workspace = true }
qrap-consensus = { workspace = true }
qrap-utxo = { workspace = true }
qrap-fpga = { workspace = true }
qrap-da = { workspace = true }
qrap-fee-splitter = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
rand = { workspace = true }
chrono = { workspace = true }
hex = { workspace = true }
