[package]
name = "qrap-node"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[[bin]]
name = "qrap-node"
path = "src/main.rs"

[dependencies]
qrap-crypto = { workspace = true }
qrap-net = { workspace = true }
qrap-consensus = { workspace = true }
qrap-utxo = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tokio = { workspace = true }
hex = { workspace = true }
anyhow = { workspace = true }
chrono = { workspace = true }
