[package]
name = "qrap-stark"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
bincode = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
qrap-crypto = { workspace = true }
qrap-fpga = { workspace = true, optional = true }

[features]
default = []
mock = []
versal = []
aws-f1 = ["qrap-fpga/aws-f1"]
